### ISSUE TITLE
Improve gather metric pipeline with other deployments [tracker]

### ISSUE THREAD

**Issue by pacospace** [AICoE/aicoe-ci#120]
**Is your feature request related to a problem? Please describe.**
Improve gather metric pipeline with other deployments

**Describe the solution you'd like**
- [ ] Add Seldon deployment (https://github.com/AICoE/aicoe-ci/issues/121)
- [ ] Add KFserving deployment
- [ ] Add combination with NeuralMagic https://neuralmagic.com/

**Describe alternatives you've considered**

**Additional context**

**Comment by pacospace** [comment]
Depends-On: https://github.com/AICoE/aicoe-ci/issues/121
